# Generated by Django 5.0 on 2023-12-29 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=50)),
                ('u_email', models.EmailField(max_length=50)),
                ('u_pass1', models.CharField(max_length=50)),
                ('u_pass2', models.CharField(max_length=50)),
            ],
        ),
    ]
